spring:
  application:
    name: LiftLog
  docker:
    compose:
      enabled: false
  datasource:
    url: ${LIFTLOG_DB_URL:jdbc:postgresql://localhost:5432/liftlog}
    username: ${LIFTLOG_DB_USERNAME:postgres}
    password: ${LIFTLOG_DB_PASSWORD:postgres}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: ${LIFTLOG_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
